### ISSUE TITLE
How to deal with unavailable preCICE data structure

### ISSUE THREAD

**Issue by davidscn** [precice/6dof-rigid-body-solver#5]
This issue is intended to discuss the general future layout of this solver and remedies:
There are two general cases, which lead here to problems:
1. The adapter uses deprecated data structures from preCICE, which are not any more present
2. The adapter uses preCICE structure, which is still there, but according to @fsimonis , this won't be accessible in the future, since the accessibility will be restricted to the solverinteface

We could either copy all (also deprecated) data structures and used functionalities e.g. in `6dof/include` directory or implement whatever is necessary to keep the functionality independent. Affected is currently (on top level) the functionality of `io/TXTTableWriter.hpp`, `utils/Dimensions.hpp`, `MeshHandle.hpp` and `constants.hpp`. Depending on which further subroutines are used by these headers, this task might be rather large.

**Comment by uekerman** [comment]
We should replace preCICE data structures with independent implementations in the 6dof solver. But most of the things can just be deleted, I guess. For the moment, it is sufficient if the solver has minimal functionality: 
* no output than printing the center coordinates, velocity, acceleration on `stdout`. 
* the solver should define its own mesh. It is sufficient to define a circle of N equidistant vertices. 

Afterwards, we should only implement additional features on demand only.
